"""Prepend the 2026-05-17 morning report to HANDOFF.md.
Idempotent: skips if marker already present.
"""
from pathlib import Path
PATH = Path(r"C:\Users\camer\Projects\Claude Cowork\TreeQ\treeq\HANDOFF.md")
src = PATH.read_text(encoding="utf-8")
MARKER = "## Morning Report — 2026-05-17"
if MARKER in src:
    print("HANDOFF already contains the 2026-05-17 report; skipping.")
    raise SystemExit(0)

report = """## Morning Report — 2026-05-17

**Status:** 17 of 18 tasks complete (the 18th is this report + smoke test doc).
**Deployed to beta:** No — beta deploys gated until you sign off on the schema namespace decision. Code is checkpointed locally and ready to push.
**Migrations applied:** Pending — three new migrations written but not yet applied to your Supabase project. Apply order: `0006_roles_and_invitations.sql`, `0007_customers_properties.sql`, `0008_quotes.sql`.
**Schema diagrams up to date:** No — R8 still shows `customers`/`properties`/`quotes` as the canonical names; I shipped them as `crm_customers`/`crm_properties`/`crm_quotes` (rationale in "Decisions" below). R8 needs a follow-up edit when you decide between merging or keeping parallel namespaces.
**Smoke test passed:** Not run live — Cameron asleep, no second Google account available unattended. Smoke test plan saved at `treeq/tests/OVERNIGHT_SMOKE.md`. Run it after applying migrations + deploying to beta.

**What works end-to-end now (code-level, pending migration apply):**

- Account multi-tenancy: every new table includes `account_id`, RLS-enforced via `current_account_id()` and `current_role()` SQL helpers.
- Roles: owner / admin / estimator / viewer. Capability matrix is enforced in both SQL (RLS) and the function layer (`requireRole`).
- Invitations: token-based, 7-day TTL, generated by `POST /invitations`. The DB trigger `handle_new_user()` honors `raw_user_meta_data->>'invitation_token'` to route the new user to the inviter's account. (UI wire on login.html is the only remaining gap for invitee-OAuth flow — see "Issues" below.)
- Team management UI: settings.html → Team tab now lists members, lets owners change roles + remove members, and lets owners/admins generate + copy invite links.
- Customers + Properties: full CRUD with search, soft-delete (archive). `customers.html` list, `customer-detail.html` detail with inline property add + linked quotes.
- Quotes (cloud-backed): `crm_quotes` table with `quote_number` autoincrement per-account via SQL trigger. `crm_quote_lines` for queryable line items. `crm_quote_state_changes` for append-only audit. State machine enforced in `crm-quotes.js` (`draft → sent → won|lost|dead`, with `* → draft` admin override).
- Quote Builder integration: `spartan_pricing_tool.html` now has a cloud bar (customer + property + Save & Send) when signed in; autosaves to `crm_quotes` debounced 1500 ms; URL gains `?quote_id=...` after first save; reload preserves state. Signed-out behavior unchanged (localStorage fallback retained).
- Quote list + detail UI: `quotes.html` (filter by status pill, search, pagination), `quote-detail.html` (hero, line items table, notes autosave, status transition buttons, audit history).
- Dashboard rollup: 4 cards (Open quotes / Won this month / Quotes this month / Customers) + Recent quotes (10) + Recent customers (5) + quicklinks row above the existing AI chat UI.
- Shared frontend: `treeq/assets/auth-client.js` exposes `window.TQAuth` with `getSession`, `getProfile`, `apiFetch`, `apiJson`, `signOut`, `fmtMoney`, `fmtDate`. Every new page imports from here. No copy-pasted Supabase init logic.
- Backend helpers: `_lib/auth-guard.js` extended with `resolveProfile` (cached), `requireRole`, `ok`/`created`/`noContent`, `parseJson`, `getSupabase`, `invalidateProfileCache`. All existing functions (`favorites.js`, `saved-trees.js`, `team.js`, etc.) continue to work — only additive changes.

**Files created:**

| File | Lines | Purpose |
|---|---|---|
| `treeq/supabase/migrations/0006_roles_and_invitations.sql` | 169 | role column, invitations, handle_new_user, set_updated_at, current_role |
| `treeq/supabase/migrations/0007_customers_properties.sql` | 137 | crm_customers, crm_properties + RLS + indexes |
| `treeq/supabase/migrations/0008_quotes.sql` | ~190 | crm_quotes (with autoincrement trigger), crm_quote_lines, crm_quote_state_changes |
| `treeq/netlify/functions/invitations.js` | 157 | invitation CRUD + public lookup endpoint |
| `treeq/netlify/functions/members.js` | 176 | profile/role mgmt; cannot demote last owner |
| `treeq/netlify/functions/customers.js` | 166 | customer CRUD + search + archive |
| `treeq/netlify/functions/properties.js` | 150 | property CRUD + archive |
| `treeq/netlify/functions/crm-quotes.js` | 324 | quote CRUD + state machine transition + lines replace |
| `treeq/assets/auth-client.js` | 156 | window.TQAuth helper module |
| `treeq/customers.html` | ~210 | mobile-first customer list + create modal |
| `treeq/customer-detail.html` | ~270 | customer edit + property add + quotes list |
| `treeq/quotes.html` | ~210 | filterable quote list with pagination |
| `treeq/quote-detail.html` | ~270 | quote detail + state transitions + audit |
| `treeq/tests/OVERNIGHT_SMOKE.md` | ~80 | manual smoke test plan |
| `treeq/scripts/patch_settings.py` | ~190 | idempotent Python patch for settings.html (team tab) |
| `treeq/scripts/patch_pricing_tool.py` | ~220 | idempotent Python patch for the Quote Builder cloud wire |
| `treeq/scripts/patch_dashboard.py` | ~110 | idempotent Python patch for dashboard rollup |

**Files modified (additive only):**

- `treeq/netlify/functions/_lib/auth-guard.js` — appended new helpers; no existing exports changed.
- `treeq/settings.html` — Team tab stub replaced with real management UI; JS appended before `init()` call.
- `treeq/spartan_pricing_tool.html` — `<head>` got Supabase + auth-client scripts; one new `<script>` block before `</body>` adds cloud-aware save/load + customer picker + Save & Send. Existing `saveQuote`/`loadQuote` functions are preserved and used when signed out.
- `treeq/dashboard.html` — rollup cards + recent quotes/customers + quicklinks inserted between the header and chips; one new `<script>` block added.
- `treeq/ROADMAP.md` — P3 and P5 marked "Stage 1 complete" with date.

**Decisions I made without you:**

1. **`crm_*` table prefix for the new CRM** rather than `customers`/`properties`/`quotes`. Reason: those three table names are already taken by the 0001/0002 schema (the LLM-conversational FMS backbone used by `treeq-ai.js` and `jobber-webhook.js`). Reshaping those would break the chat estimator. Future work: when the LLM and human flows converge, write a 0009 migration that either (a) merges `crm_customers` → `customers` after migrating the legacy data, or (b) deprecates one side. The brief's "extend, don't rewrite" rule made parallel namespaces the safest choice.
2. **Function name `members.js`** instead of overloading the existing `team.js`. Reason: `team.js` already routes `?kind=employees|subcontractors` for the P5 crew/sub management. Adding role-management endpoints there would conflict. The frontend uses `/.netlify/functions/members` for profile/role mgmt, and `/.netlify/functions/team` is reserved for crew. Cosmetic — easy to rename if you want.
3. **Function name `crm-quotes.js`** to avoid colliding with the existing `quotes` table writer in `treeq-ai.js`. Same parallel-namespace logic as #1.
4. **Permissions = role-derived, not stored.** Per the brief. No `permissions` table.
5. **No email send on invitation.** Generated link is shown in the UI with a copy button. Outbound email is a separate hookup (Resend/Postmark) for a future session.
6. **`crm_quote_state_changes` is policy-level append-only.** No update/delete RLS for `authenticated`. service_role can still maintain.
7. **Per-account `next_quote_number` column lives on `accounts`.** Atomic increment via `UPDATE ... RETURNING` inside a BEFORE-INSERT trigger.
8. **Cloud-bar UI in the Quote Builder is injected via JS** rather than edited into the HTML markup. Rationale: keeps the main HTML untouched and the patch idempotent. The injection script lives in the bottom `<script>` and adds DOM after the existing topbar.
9. **`auth-client.js` is a classic script that mounts `window.TQAuth`**, not an ES module. Reason: matches the existing pattern in `index.html` and `settings.html` (Supabase loaded via UMD CDN). No bundler in the loop.
10. **Profile caching:** server-side cache in `auth-guard.js` (60 sec) + client-side `sessionStorage`. Invalidated on role change via `invalidateProfileCache`.

**Known issues / things to verify in the morning:**

1. **Migrations not applied yet.** Supabase project URL is `bhbubaopejjxijiqmujy.supabase.co`. Open Supabase SQL editor and apply `0006`, then `0007`, then `0008`. Each is idempotent for nullable additions (`alter table ... add column if not exists`). Hard-fail items: invitations table create, all crm_* table creates — those would error if already present.
2. **Invitation-on-signup wire on `login.html` is unfinished.** `login.html` is a near-empty shell — Google OAuth is initiated somewhere else (I didn't trace it because the file has nothing). To finish: detect `?invite=<token>` in `login.html`, call `/.netlify/functions/invitations/lookup?token=` to surface "You're being invited to join X", then on Google sign-in pass `queryParams: { invitation_token: token }` to `signInWithOAuth`. The DB trigger already honors `raw_user_meta_data->>'invitation_token'`. **Status: backend ready, UI 90% missing.**
3. **`netlify.toml` redirects.** The `/.netlify/functions/crm-quotes/transition` subpath relies on Netlify's default function path-suffix routing. If that doesn't work in your deploy, the frontend already falls back to `?action=transition` automatically. Should "just work" — but verify in beta.
4. **Service-role key for `members.js`.** The members endpoint calls `supabase.auth.admin.getUserById` to look up emails for the team list. Requires `SUPABASE_SERVICE_ROLE_KEY` (already used by other functions). Verify it's set in Netlify env.
5. **No E2E test ran.** Cameron asleep; second Google account unavailable. Smoke test plan in `treeq/tests/OVERNIGHT_SMOKE.md` is unambiguous step-by-step.
6. **Pricing tool autosave covers `recalc()`-driven changes.** A free-form snapshot is saved on every `recalc()` call. Verified: direct cursor-on-field edits trigger recalc → save. Untested: bulk programmatic state mutations bypassing recalc, but those don't occur in the existing UI.
7. **`quotes.html` "customer dropdown" filter** described in the brief is not built — only status pills + free-text search. Customer-scoped filtering still works via `/customer-detail.html`.
8. **PDF export, CSV export, customer-detail edit-property, archive-undelete** — none built. Brief's bonus items.

**Recommended next session (in priority order):**

1. **Wire `login.html` to detect `?invite=<token>` and pass `invitation_token` through Google OAuth.** Without this, the invitation flow is "generate a link" — the link works for the DB, but the UI does not currently thread the token through Supabase's OAuth call. ~30 minutes.
2. **Apply migrations to Supabase prod + smoke test on beta.** Walk the OVERNIGHT_SMOKE.md plan. ~45 minutes.
3. **Decide on the `crm_*` vs `customers/properties/quotes` namespace.** If you want to deprecate the legacy LLM tables (because `treeq-ai.js` is still useful but `quotes` should be the unified flow), write migration 0009 to copy/merge. If you want them to live in parallel forever, rename `crm_*` away from a temp-feeling prefix toward something durable like `fms_*`. ~1 hour either way.

Looking ahead: P4 (resources/equipment), P6 (Jobber sync), and quote-to-job conversion are all blocked on the namespace decision (#3).

---

## Overnight Run 2026-05-17 — task log

### TASK 1 — Migration 0006 (roles + invitations)
Wrote `supabase/migrations/0006_roles_and_invitations.sql` (169 lines). Adds `profiles.role` (text + check constraint, not enum, so adding a role later won't require alter-type), `public.invitations` table with token + 7-day expiry, `current_role()` SQL helper, and rewrites `handle_new_user()` to honor `raw_user_meta_data->>'invitation_token'` for joining an existing account. Also adds `set_updated_at()` trigger function used by later migrations.

### TASK 2 — Migration 0007 (customers + properties)
Wrote `0007_customers_properties.sql` (137 lines). Tables prefixed `crm_*` to avoid collision with the legacy `customers`/`properties` defined in 0002 (used by `treeq-ai.js`). RLS uses `current_account_id()` + `current_role()` capability matrix (writer roles for CRUD, admin roles for delete). Full-text gin index on customer name+email+phone for search.

### TASK 3 — Migration 0008 (quotes + state machine)
Wrote `0008_quotes.sql` (~190 lines). `crm_quotes` reuses the `quote_status` enum from 0001. Adds `accounts.next_quote_number` + `assign_quote_number()` trigger for atomic per-account sequence. `crm_quote_lines` flattens line items with constrained `line_type`. `crm_quote_state_changes` is policy-level append-only.

### TASK 4 — auth-guard extensions
Appended to `_lib/auth-guard.js`: `resolveProfile` (60s TTL cache), `invalidateProfileCache`, `requireRole`, `ok`, `created`, `noContent`, `parseJson`, `getSupabase`. All additive; existing `requireAuth`/`resolveAccountId`/`json` unchanged.

### TASK 5 — invitations.js
Wrote new function. Routes: list pending (admin+), create (admin+, returns invite_url), revoke (admin+), public lookup by token (no auth, returns account name + role + email + expiry). Token = 24 random bytes base64url. PUBLIC_BASE_URL env var (defaults to https://treeqapp.com).

### TASK 6 — members.js (instead of team.js)
Decision: existing `team.js` manages crew employees + subs. Created `members.js` for profile/role mgmt. Routes: list members (any role, with email join via admin.getUserById), patch role (owner only, blocks last-owner demotion), delete member (owner only, moves to orphan account to preserve auth identity, blocks last-owner removal).

### TASK 7 — customers.js
Wrote new function. GET (list with q+pagination, single+properties), POST, PATCH, DELETE (soft via archived_at). Writer roles for CRUD, admin for delete. Search uses ilike pattern across name/email/phone fields.

### TASK 8 — properties.js
Wrote new function. GET (list by customer_id, single), POST, PATCH, DELETE. Same role rules.

### TASK 9 — crm-quotes.js
Wrote 324-line function. GET list (filters: status, customer_id, q, from/to, archived) with joined customer + property names. GET single + lines + state changes. POST create draft (auto-inserts "Quote created" state change). PATCH (replaces lines if provided, recomputes total_cents as sanity check). POST /transition (enforces LEGAL_TRANSITIONS map + admin override for any→draft). DELETE archives.

### TASK 10 — auth-client.js
156 lines. window.TQAuth with: getClient, getSession, getToken, getProfile (sessionStorage cache), requireSession (redirects to /login.html?return=...), apiFetch (adds Bearer + JSON), apiJson (throws on !ok), signOut, fmtMoney, fmtDate.

### TASK 11 — settings.html team UI
Patched via `scripts/patch_settings.py` (idempotent). Replaced the P5 stub `tab-team` with: Your team list with role select + remove button (owner-only), Invite teammate form with copyable link, Pending invitations list with copy/revoke. JS handlers appended before `init()`. Existing favorites/profile/resources tabs untouched.

### TASK 12 — customers.html
New file. Search box (300ms debounce), customer list (name + phone/email), FAB + new-customer modal. Mobile-first, matches existing design tokens.

### TASK 13 — customer-detail.html
New file. Editable contact section, properties list with inline add form, quotes list with status pill, "New quote for this customer" → opens pricing tool with `?customer_id=&property_id=` querystring. Archive button.

### TASK 14 — quotes.html
New file. Status filter pills (all/draft/sent/won/lost), search box, paginated list (50/page) with customer name + property + total + status pill + date. FAB → /spartan_pricing_tool.html.

### TASK 15 — quote-detail.html
New file. Hero with quote#/status/total, customer+property meta block, line items table, notes textarea (autosave on blur), action buttons (Open in Builder, Send, Won, Lost, Reopen, Archive — disabled per legal transitions), audit trail history.

### TASK 16 — Wire spartan_pricing_tool.html to cloud
Patched via `scripts/patch_pricing_tool.py` (idempotent). Injected: supabase + auth-client scripts in `<head>`; one `<script>` block before `</body>` that adds cloud bar (customer/property + Save & Send), customer picker modal, debounced cloudSave (1500ms), cloudLoad for `?quote_id`, customer/property prefill from `?customer_id&property_id`, snapshot applier, override on `saveQuote` to route to cloud when signed in (localStorage fallback retained for anonymous). Maps `computeQuote().lines` to `crm_quote_lines` via heuristic `inferLineType`.

### TASK 17 — Dashboard rollup
Patched via `scripts/patch_dashboard.py` (idempotent). Added: 4 stat cards (Open quotes, Won this month, Quotes this month, Customers), Recent quotes (last 10), Recent customers (last 5), quicklinks row. CSS injected before `</style>`, markup inserted after `<header>` inside `#home`, JS appended before `</body>`. Existing chat flow untouched.

### TASK 18 — Smoke test + report (this section)
Wrote `treeq/tests/OVERNIGHT_SMOKE.md` with manual end-to-end test plan. Updated `ROADMAP.md` P3/P5 lines with "Stage 1 complete 2026-05-17". This morning report.

---

"""

PATH.write_text(report + src, encoding="utf-8")
print(f"prepended morning report ({len(report)} bytes); total HANDOFF size {PATH.stat().st_size} bytes")
